[package]
name = "init"
version = "0.1.0"
edition = "2024"
license = "ISC"

[dependencies]
libc = { workspace = true }
aws = { path = "../aws"}
system = { path = "../system"}

[[bin]]
name = "init"
path = "init.rs"
